In [228]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import psycopg2
from psycopg2 import sql
import psycopg2.extras as extras
import sqlalchemy
from sqlalchemy import create_engine, text

In [229]:
username = 'postgres'
password = 'Momina123'
host = 'localhost'
port = '5432'
database = 'Ecommerce_db'
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [230]:
with engine.connect():
    print("Connected Successfully to Ecomerce_db")

Connected Successfully to Ecomerce_db

__Customer Table__

In [231]:
customers = pd.read_csv("olist_customers_dataset.csv")

In [232]:
customers.sample()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
84032,98e5352560be36e212fd37586d7f6409,c4c088737a539f84fab061a3299dfe58,22753,rio de janeiro,RJ

In [233]:
customers.shape

(99441, 5)

In [234]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [235]:
customers.describe(include='all')

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [236]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [237]:
customers.duplicated().sum()

np.int64(0)

__Order Items Table__

In [238]:
order_items= pd.read_csv("olist_order_items_dataset.csv")

In [239]:
order_items.sample()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
15320,22f3a2b22f414d974640db425514794d,1,07fe9ffbb84b9d22610d79efb16e81a7,e84ad2127668df3aafc6b73531a0beb8,2018-08-10 13:45:18,65.0,17.39

In [240]:
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

In [241]:
order_items.shape

(112650, 7)

In [242]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

In [243]:
order_items.describe(include='all')

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,112650,112650.000000,112650,112650,112650,112650.000000,112650.000000
unique,98666,NaN,32951,3095,NaN,NaN,NaN
top,8272b63d03f5f79c56e9e4120aec44ef,NaN,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,NaN,NaN,NaN
freq,21,NaN,527,2033,NaN,NaN,NaN
mean,NaN,1.197834,NaN,NaN,2018-01-07 15:36:52.192685312,120.653739,19.990320
min,NaN,1.000000,NaN,NaN,2016-09-19 00:15:34,0.850000,0.000000
25%,NaN,1.000000,NaN,NaN,2017-09-20 20:57:27.500000,39.900000,13.080000
50%,NaN,1.000000,NaN,NaN,2018-01-26 13:59:35,74.990000,16.260000
75%,NaN,1.000000,NaN,NaN,2018-05-10 14:34:00.750000128,134.900000,21.150000
max,NaN,21.000000,NaN,NaN,2020-04-09 22:35:08,6735.000000,409.680000
std,NaN,0.705124,NaN,NaN,NaN,183.633928,15.806405

In [244]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [245]:
order_items.duplicated().sum()

np.int64(0)

__Payments Table__

In [246]:
payments = pd.read_csv("olist_order_payments_dataset.csv")

In [247]:
payments.sample()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
39651,6fc237eec099504ef31e3f3896596be7,1,boleto,1,43.41

In [248]:
payments.shape

(103886, 5)

In [249]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [250]:
payments.describe(include='all')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

In [251]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [252]:
payments.duplicated().sum()

np.int64(0)

__Reviews Table__

In [253]:
reviews = pd.read_csv("olist_order_reviews_dataset.csv")

In [254]:
reviews.sample()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
66258,bec949a191b23054c824a8b0b0f5cb3c,54f334d6a9d60b69dae5409327f73645,5,NaN,NaN,2017-12-01 00:00:00,2017-12-01 14:42:11

In [255]:
reviews.shape

(99224, 7)

In [256]:
reviews['review_creation_date'] = pd.to_datetime(reviews['review_creation_date'])
reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'])

In [257]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 5.3+ MB

In [258]:
reviews.describe(include='all')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,99224,99224,99224.000000,11568,40977,99224,99224
unique,98410,98673,NaN,4527,36159,NaN,NaN
top,7b606b0d57b078384f0b58eac1d41d78,c88b1d1b157a9999ce368f218a407141,NaN,Recomendo,Muito bom,NaN,NaN
freq,3,3,NaN,423,230,NaN,NaN
mean,NaN,NaN,4.086421,NaN,NaN,2018-01-12 20:49:23.948238336,2018-01-16 00:23:56.977938688
min,NaN,NaN,1.000000,NaN,NaN,2016-10-02 00:00:00,2016-10-07 18:32:28
25%,NaN,NaN,4.000000,NaN,NaN,2017-09-23 00:00:00,2017-09-27 01:53:27.249999872
50%,NaN,NaN,5.000000,NaN,NaN,2018-02-02 00:00:00,2018-02-04 22:41:47.500000
75%,NaN,NaN,5.000000,NaN,NaN,2018-05-16 00:00:00,2018-05-20 12:11:21.500000
max,NaN,NaN,5.000000,NaN,NaN,2018-08-31 00:00:00,2018-10-29 12:27:35
std,NaN,NaN,1.347579,NaN,NaN,NaN,NaN

In [259]:
reviews['review_comment_title'] = reviews['review_comment_title'].fillna('No title')
reviews['review_comment_message'] = reviews['review_comment_message'].fillna('No Comment')

In [260]:
reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [261]:
reviews.duplicated().sum()

np.int64(0)

In [262]:
reviews = reviews.drop_duplicates(subset=['review_id'],keep='first')

__Orders Table__

In [263]:
orders = pd.read_csv("olist_orders_dataset.csv")

In [264]:
orders.sample()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
10078,ff3d961f941d0784936dbe5da739575e,13c63b62948447f955a98910800ca8f6,delivered,2018-03-07 18:00:44,2018-03-07 18:15:44,2018-03-09 20:08:31,2018-04-10 03:05:01,2018-03-28 00:00:00

In [265]:
orders.shape

(99441, 8)

In [266]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at']=pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date']= pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date']= pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date']=pd.to_datetime(orders['order_estimated_delivery_date'])

In [267]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [268]:
orders.describe(include='all')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,NaN,NaN,NaN,NaN,NaN
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,NaN,NaN,NaN,NaN,NaN
freq,1,1,96478,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,2017-12-31 08:43:12.776581120,2017-12-31 18:35:24.098800128,2018-01-04 21:49:48.138278656,2018-01-14 12:09:19.035542272,2018-01-24 03:08:37.730111232
min,NaN,NaN,NaN,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00
25%,NaN,NaN,NaN,2017-09-12 14:46:19,2017-09-12 23:24:16,2017-09-15 22:28:50.249999872,2017-09-25 22:07:22.249999872,2017-10-03 00:00:00
50%,NaN,NaN,NaN,2018-01-18 23:04:36,2018-01-19 11:36:13,2018-01-24 16:10:58,2018-02-02 19:28:10.500000,2018-02-15 00:00:00
75%,NaN,NaN,NaN,2018-05-04 15:42:16,2018-05-04 20:35:10,2018-05-08 13:37:45,2018-05-15 22:48:52.249999872,2018-05-25 00:00:00
max,NaN,NaN,NaN,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12 00:00:00

In [269]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [270]:
orders.duplicated().sum()

np.int64(0)

__Products Table__

In [271]:
products = pd.read_csv("olist_products_dataset.csv")

In [272]:
products.sample()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
11788,9493c042ad7ecfd2c0123733b2c310ff,automotivo,56.0,708.0,3.0,1700.0,30.0,30.0,30.0

In [273]:
products.shape

(32951, 9)

In [274]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [275]:
products.describe(include='all')

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32341,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
unique,32951,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1e9e8ef04dbcff4541ed26657ea517e5,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,NaN,NaN,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,NaN,NaN,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,NaN,NaN,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,NaN,NaN,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,NaN,NaN,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [276]:
products['product_category_name'] = products['product_category_name'].fillna('Unknown')
products['product_name_lenght'] = products['product_name_lenght'].fillna(0)
products['product_description_lenght'] = products['product_description_lenght'].fillna(0)
products['product_photos_qty'] = products['product_photos_qty'].fillna(0)
cols = ['product_weight_g','product_length_cm','product_height_cm','product_width_cm']
for c in cols:
    products[c] = products[c].fillna(products[c].median())

In [277]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [278]:
products.duplicated().sum()

np.int64(0)

__Sellers Table__

In [279]:
sellers = pd.read_csv("olist_sellers_dataset.csv")

In [280]:
sellers.sample()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2819,38874e327ce94d11390b96eb42d61928,8577,itaquaquecetuba,SP

In [281]:
sellers.shape

(3095, 4)

In [282]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [283]:
sellers.describe(include='all')

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095.000000,3095,3095
unique,3095,NaN,611,23
top,3442f8959a84dea7ee197c632cb2df15,NaN,sao paulo,SP
freq,1,NaN,694,1849
mean,NaN,32291.059451,NaN,NaN
std,NaN,32713.453830,NaN,NaN
min,NaN,1001.000000,NaN,NaN
25%,NaN,7093.500000,NaN,NaN
50%,NaN,14940.000000,NaN,NaN
75%,NaN,64552.500000,NaN,NaN
max,NaN,99730.000000,NaN,NaN

In [284]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [285]:
sellers.duplicated().sum()

np.int64(0)

__Category Table__

In [286]:
category = pd.read_csv("product_category_name_translation.csv")

In [287]:
category.sample()

,product_category_name,product_category_name_english
26,moveis_cozinha_area_de_servico_jantar_e_jardim,kitchen_dining_laundry_garden_furniture

In [288]:
category.shape

(71, 2)

In [289]:
category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [290]:
category.describe(include='all')

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [291]:
category.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [292]:
category.duplicated().sum()

np.int64(0)

In [293]:
category[category["product_category_name"]=="pc_gamer"]

Empty DataFrame
Columns: [product_category_name, product_category_name_english]
Index: []

In [294]:
products["product_category_name"].value_counts()

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 74, dtype: int64

__Geolocation Table__

In [295]:
geolocation= pd.read_csv("olist_geolocation_dataset.csv")

In [296]:
geolocation.sample()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
617670,36512,-21.179177,-43.019674,tocantins,MG

In [297]:
geolocation.shape

(1000163, 5)

In [298]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [299]:
geolocation.describe(include='all')

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1.000163e+06,1.000163e+06,1.000163e+06,1000163,1000163
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,135800,404268
mean,3.657417e+04,-2.117615e+01,-4.639054e+01,NaN,NaN
std,3.054934e+04,5.715866e+00,4.269748e+00,NaN,NaN
min,1.001000e+03,-3.660537e+01,-1.014668e+02,NaN,NaN
25%,1.107500e+04,-2.360355e+01,-4.857317e+01,NaN,NaN
50%,2.653000e+04,-2.291938e+01,-4.663788e+01,NaN,NaN
75%,6.350400e+04,-1.997962e+01,-4.376771e+01,NaN,NaN
max,9.999000e+04,4.506593e+01,1.211054e+02,NaN,NaN

In [300]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [301]:
geolocation['geolocation_zip_code_prefix'].nunique()

19015

In [302]:
geolocation = geolocation.drop_duplicates(subset=['geolocation_zip_code_prefix'], keep='first')
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
5,1012,-23.547762,-46.635361,são paulo,SP
...,...,...,...,...,...
999774,99955,-28.107588,-52.144019,vila langaro,RS
999780,99970,-28.345143,-51.876926,ciriaco,RS
999786,99910,-27.863500,-52.084760,floriano peixoto,RS
999803,99920,-27.858716,-52.300403,erebango,RS
999846,99952,-28.160371,-51.936922,santa cecilia do sul,RS

In [303]:
geolocation.duplicated(subset=['geolocation_zip_code_prefix']).sum()

np.int64(0)

__Merge All Tables__

In [304]:
df= customers.merge(orders, on='customer_id', how='inner')
df= df[df['order_status'] =='delivered']

In [305]:
df_obys = df.groupby('customer_state').agg(orderbystate = ('order_id','nunique')).reset_index()

In [306]:
df = df.merge(df_obys, on='customer_state', how='left')

__Revenu by State__

In [307]:
new = customers.merge(orders, on='customer_id', how='inner')
new_df= new.merge(order_items, on='order_id', how='inner')

In [308]:
Revenue = new_df.groupby('customer_state').agg(total_revenue = ('price','sum')).reset_index()

In [309]:
df = df.merge(Revenue, on='customer_state', how='left')

__Customer By State__

In [310]:
customer_by_state = df.groupby('customer_state').agg(total_customers = ('customer_id','count')).reset_index()

In [311]:
df = df.merge(customer_by_state, on='customer_state', how='left')

__Product Volume__

In [312]:
products['product_volume'] = products['product_length_cm'] * products['product_height_cm']*products['product_width_cm']
products['product_volume']

0         2240.0
1        10800.0
2         2430.0
3         2704.0
4         4420.0
          ...
32946    64000.0
32947     4864.0
32948     5103.0
32949     8060.0
32950      168.0
Name: product_volume, Length: 32951, dtype: float64

In [313]:
df = df.merge(order_items, on='order_id', how='left')

In [314]:
df = df.merge(products, on='product_id', how='left')

In [315]:
def reviews_checker(txt):
    if txt <= 2:
        return 'Negative'
    elif txt == 3:
        return 'Normal'
    else:
        return 'Positive'

In [316]:
df['Reviews Checker'] = reviews['review_score'].apply(reviews_checker)

In [317]:
df = df.merge(reviews, on='order_id', how='left')
df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_height_cm,product_width_cm,product_volume,Reviews Checker,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,64.0,31.0,107136.0,Positive,88b8b52d46df026a9d1ad2136a59b30b,4.0,No title,No Comment,2017-05-26,2017-05-30 22:34:40
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,15.0,40.0,53400.0,Positive,02fc48a9efa3e3d0f1a8ea26507eeec3,5.0,No title,No Comment,2018-01-30,2018-02-10 22:43:29
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,52.0,17.0,45968.0,Positive,5ad6695d76ee186dc473c42706984d87,5.0,No title,No Comment,2018-06-15,2018-06-15 12:10:59
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,51.0,28.0,79968.0,Positive,059a801bb31f6aab2266e672cab87bc5,5.0,No title,No Comment,2018-03-29,2018-04-02 18:36:47
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,15.0,35.0,23625.0,Positive,8490879d58d6c5d7773f2739a03f089a,5.0,a melhor nota,O baratheon è esxelente Amo adoro o baratheon,2018-08-10,2018-08-17 01:59:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110488,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,...,22.0,23.0,11132.0,NaN,36e2cdbaa9f639b57c53b37ac798fee8,4.0,Recomendo,No Comment,2018-04-14,2018-04-28 11:15:04
110489,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,...,24.0,22.0,13200.0,NaN,b273b431c3aedb4eed18643309652940,5.0,No title,No Comment,2018-04-12,2018-04-16 10:36:05
110490,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,...,20.0,18.0,9000.0,NaN,fa4f16891e6b2edd1354668d07f5648b,1.0,Chateada,Esperava qualidade no atendimento e estou tend...,2018-05-04,2018-05-08 01:41:07
110491,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,...,13.0,14.0,3458.0,NaN,0bcdc9e450ea500811a8d39ee993cd47,5.0,No title,No Comment,2017-11-17,2017-11-19 23:34:18
110492,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,...,5.0,11.0,880.0,NaN,d95d701d062d2bb88041768a63aa750d,5.0,No title,"Produto chegou bem antes do prazo , gostei mui...",2017-12-27,2017-12-27 23:21:06

In [318]:
total = payments.groupby('order_id').agg(total_payments = ('payment_value','sum')).reset_index()

In [319]:
df = df.merge(total , on='order_id', how='left')

In [320]:
Average_order = total['total_payments'].mean()
Average_order

np.float64(160.9902666934835)

In [321]:
total_revenue = total['total_payments'].sum()
total_revenue

np.float64(16008872.12)

__ORDERS__

In [322]:
orders['order_year'] = orders['order_purchase_timestamp'].dt.year
orders['order_month'] = orders['order_purchase_timestamp'].dt.month
orders['month_name'] = orders['order_purchase_timestamp'].dt.month_name()
orders['day_of_week'] = orders['order_purchase_timestamp'].dt.day_name()
orders['quarter'] = 'Q' + orders['order_purchase_timestamp'].dt.quarter.astype(str)
orders['is_weekend'] = orders['order_purchase_timestamp'].dt.dayofweek>=5
orders['weekend_order'] = orders['is_weekend'].map({True:'Yes', False:'No'})
orders['delivery_days'] = (orders['order_delivered_customer_date']-orders['order_purchase_timestamp']).dt.days
orders['delivery_gap'] = (orders['order_estimated_delivery_date']-orders['order_delivered_customer_date']).dt.days

In [323]:
def estimation(txt):
    if txt > 0:
        return 'Early'
    elif txt == 0:
        return 'On time'
    else:
        return 'Late'

In [324]:
orders['delivery_gap'] = orders['delivery_gap'].apply(estimation)

In [325]:
df = df.merge(orders[['order_id','order_year','order_month','month_name','day_of_week','quarter','is_weekend','weekend_order','delivery_days','delivery_gap']], on='order_id', how='left')

In [326]:
df = df.merge(payments[['payment_type','payment_installments','order_id']], on='order_id', how='left')

In [327]:
order_item_sum = order_items.groupby('order_id')[['price','freight_value']].sum().reset_index()

In [328]:
df = df.merge(order_item_sum , on='order_id', how='left')

In [329]:
df['total_charges'] = df['price_y']+ df['freight_value_y']

In [330]:
customers.to_csv('customers_cleaned.csv', index=False)

In [331]:
order_items.to_csv('order_items_cleaned.csv', index=False)

In [332]:
payments.to_csv('payments_cleaned.csv', index=False)

In [333]:
reviews.to_csv('reviews_cleaned.csv', index=False)

In [334]:
orders.to_csv('orders_cleaned.csv', index=False)

In [335]:
products.to_csv('products_cleaned.csv', index=False)

In [336]:
sellers.to_csv('sellers_cleaned.csv', index=False)

In [337]:
category.to_csv('category_cleaned.csv', index=False)

In [338]:
geolocation.to_csv('geolocation_cleaned.csv', index=False)

In [339]:
df.to_csv('Final_olist_for_analysis.csv',index=False)

In [340]:
tables = {
    'customers': customers,
    'sellers': sellers,
    'products':products,
    'categories': category,
    'geolocation': geolocation,
    'orders': orders,
    'orderItem': order_items,
    'payement': payments,
    'reviews': reviews,
}

In [341]:
for table_name, df in tables.items():
    try:
        with engine.begin() as conn:
            conn.execute(text(f'TRUNCATE TABLE "{table_name}" RESTART IDENTITY CASCADE'))
            df.to_sql(
                name = table_name,
                con = conn,
                if_exists = 'append',
                index = False,
                method = 'multi'
            )
            print(f"{table_name} imported successfully with {len(df)} rows")
    except Exception as e:
           print(f"error in {table_name}: {e}")

print("Pipeline completed successfully")

customers imported successfully with 99441 rows
sellers imported successfully with 3095 rows
products imported successfully with 32951 rows
categories imported successfully with 71 rows
geolocation imported successfully with 19015 rows
orders imported successfully with 99441 rows
orderItem imported successfully with 112650 rows
payement imported successfully with 103886 rows
reviews imported successfully with 98410 rows
Pipeline completed successfully